Modificacion
Codeko/custom-post-parents pull request #3
Opened 2017-03-30 11:57 UTC by oscar-87

- Se ha modificado el lugar donde se le asigna el evento click al botón que borrar los items
- Se ha limpiado el código y se han renombrado las variables poniéndolas en inglés.
- Se a hecho que al seleccionar y añadir un item del select que posteriormente se seleccione automáticamente la primera opción del select "Seleccione una opción"

2017-03-30 12:19 UTC, boris-burgos requested changes
Vamos a ajustar los cambios comentados

2017-03-30 12:19 UTC, boris-burgos commented on custom-post-parents.php
> +  Text Domain:custom-post-parents
Añadir espacio después de ":"

2017-03-30 12:19 UTC, boris-burgos commented on custom-post-parents.php
> +  Domain Path: /localhost/wordpress/wp-content/languages
Este Domain Path es incorrecto

2017-03-30 12:19 UTC, boris-burgos commented on includes/CustomPostParentsAdminPage.php
> +            wp_enqueue_script( 'custom_post_parents_admin', site_url() . '/wp-content/plugins/custom-post-parents/js/custom-post-parents-admin.js');
Esta forma de referenciar el script es incorrecta, además se han eliminado las dependencias aunque estas siguen existiendo.

2017-03-30 12:19 UTC, boris-burgos commented on includes/CustomPostParentsAdminPage.php
> +        load_plugin_textdomain('custom-post-parents', false,"custom-post-parents/lang");
La carga del textdomain mejor la movemos al init o al plugins_loaded

https://developer.wordpress.org/reference/functions/load_plugin_textdomain/

2017-03-30 12:19 UTC, boris-burgos commented on js/custom-post-parents-admin.js
> +            var section=$(this).attr("data-section");
Aquí puedes usar directamente $(this).data("section");

2017-03-30 12:19 UTC, boris-burgos commented on js/custom-post-parents-admin.js
>              $(this).parents('span').remove();
Hay muchos usos del $(this), en estos casos es mejor crear una variable
var $this= $(this);
Y usarla para no ir creando instancias en cada llamada

2017-03-30 12:19 UTC, boris-burgos commented on js/custom-post-parents-admin.js
> +            $("#cpt-f-"+section+" >option[id='"+id_option+"']").show();
Este punto me crea dudas. Si hay un id=XXX el selector anterior de section no tiene sentido ya que el id debe ser único para todo el documento.
Así que o no hace falta el section o se repiten IDs

2017-03-30 12:19 UTC, boris-burgos commented on includes/CustomPostParentsAdminPage.php
> +            wp_localize_script('custom_post_parents_admin','data',$data);
Vamos a darle a la variable data un nombre más único y significativo

2017-03-30 12:19 UTC, boris-burgos commented on includes/CustomPostParentsAdminPage.php
> +                'first_option_select'=>__("Choose option",'custom-post-parents')
Vamos a darle a esta variable un nombre más intuitivo

2017-03-30 12:19 UTC, boris-burgos commented on js/custom-post-parents-admin.js
> +            var section=target.getAttribute("data-section")
Vamos a usar el data() de jQuery

2017-03-30 12:19 UTC, boris-burgos commented on js/custom-post-parents-admin.js
> +            var valActual=$(this).val();
Ponemos la variable en inglés

2017-03-30 12:19 UTC, boris-burgos commented on js/custom-post-parents-admin.js
> +            $(".custom-post-parents-selectlist-add>#defecto").attr("selected",true);
¿Por qué hacer esto aquí en vez de en la creación del option?

2017-04-03 06:59 UTC, oscar-87 commented on js/custom-post-parents-admin.js
> +            $(".custom-post-parents-selectlist-add>#defecto").attr("selected",true);
Porque lo que hago es que seleccione la primera opción siempre que le de a añadir un elemento, ya que la que el elemento añadido se va a dejar de mostrar en el select

2017-04-03 07:09 UTC, boris-burgos commented on js/custom-post-parents-admin.js
> +            $(".custom-post-parents-selectlist-add>#defecto").attr("selected",true);
Ok, pero lo estás haciendo sobre todos los selects no sobre el que se está cambiando, ¿no?

2017-04-03 07:11 UTC, boris-burgos commented on js/custom-post-parents-admin.js
> +            $("#cpt-f-"+section+" >option[id='"+id_option+"']").show();
De hecho estoy viendo que se crean multiples selects con las mismas IDs en sus options. La ID debe ser única siempre, si necesitas una ID (que no creo que la necesites) genérala con prefijo del post type o con un contador para evitar colisiones.

2017-04-03 07:31 UTC, oscar-87 commented on js/custom-post-parents-admin.js
> +            $("#cpt-f-"+section+" >option[id='"+id_option+"']").show();
Llevas razón ya que la comprobación del id es innecesaria porque es único. He omitido la parte del selector a partir del +section, quedando de la siguiente manera:

        $ul.on('click','.ntdelbutton',function(){
            var current_item=$(this);
            var section=current_item.data("section");
            $("#cpt-f-"+section).show();
            current_item.parents('span').remove();
        });

2017-04-03 07:32 UTC, oscar-87 commented on js/custom-post-parents-admin.js
>              $(this).parents('span').remove();
He creado una variable que recoge el $(this) para evitar que se repitan llamadas y hacerlo más eficiente. Queda de la siguiente manera:    
$ul.on('click','.ntdelbutton',function(){
        var current_item=$(this);
        var section=current_item.data("section");
        $("#cpt-f-"+section).show();
        current_item.parents('span').remove();
    });

2017-04-03 07:34 UTC, oscar-87 commented on js/custom-post-parents-admin.js
> +            var section=target.getAttribute("data-section")
He modificado lo que me has comentado y he eleminado la variable target, ya que con la modificación no se utiliza. Queda de la siguiente manera:

        $('.custom-post-parents-selectlist-add').change(function(event){
            var section=$(this).data("section")

2017-04-03 07:36 UTC, oscar-87 commented on js/custom-post-parents-admin.js
> +            var valActual=$(this).val();
He puesto el nombre de la variable en inglés, quedando de la siguiente manera:

var current_value=$(this).val();

2017-04-03 07:38 UTC, boris-burgos commented on js/custom-post-parents-admin.js
>              $(this).parents('span').remove();
¿Y estás seguro de que `"#cpt-f-"+section` es único?

2017-04-03 07:40 UTC, boris-burgos commented on js/custom-post-parents-admin.js
> +            var valActual=$(this).val();
Como verás en el resto del código se usa camelcase para los nombres de las variables. En general para javascript se usa camelcase. Vamos a mantenerlo así.

2017-04-04 05:47 UTC, oscar-87 reviewed
He realizado los cambios que me has propuesto y he hecho algunos más que me han parecido interesantes

2017-04-07 05:14 UTC, merged